// <auto-generated />
using Generador_de_poses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Generador_de_poses.Migrations
{
    [DbContext(typeof(PersonajesDbContext))]
    [Migration("20250830221215_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Generador_de_poses.Data.Cuerpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuerpos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Musculoso",
                            RutaImagen = "muscles.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Delgado",
                            RutaImagen = "slim.png"
                        });
                });

            modelBuilder.Entity("Generador_de_poses.Data.Expresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expresions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Normal",
                            RutaImagen = "normal.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Alegre",
                            RutaImagen = "alegre.png"
                        });
                });

            modelBuilder.Entity("Generador_de_poses.Data.Pose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Poses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Parado",
                            RutaImagen = "parado.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Agachado",
                            RutaImagen = "agachado.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
